// Generated by CoffeeScript 1.12.6
(function() {
  var Raccourcis, app,
    slice = [].slice,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  app = angular.module("app_mrc", ['ngAnimate', 'ui.bootstrap', 'ngMdIcons', 'ngTouch', 'ngClipboard']);


  /* TODO effacer le 10-08
  app.directive 'onFinishRender', ($timeout)->
      return{
          restrict: 'A',
          link: (scope, element, attr) ->
              if scope.$last == true
                  $timeout () -> console.log 'la fin du tri'
  
      }
   */

  app.controller("ctl_mrc", function($scope, $document, $location, $anchorScroll, $http, $uibModal, $window, $log, $timeout, ngClipboard, $sce) {
    var $$, MA, ajx_fl, bd_glob_dddr, bd_tous_les_bilans, broadcast_lower, cb, cursor_waiting_for, date_is_ok, dte_last_report, ess, get_bd_global_dvdp, get_bd_jeux_regies_campagnes, get_bd_levier, get_url_bilan, get_url_xy, handle_bd_gain_0, handle_bd_variation, idx_lst, init_date, is_cmp_in_bd_glob, mBackUp, marge_inf_10_exists, msg, partial_raz, present_file, rac, raz_bd_empty, set_title_variation, show, show_err, shws, stg, t, u, url_logs, url_param, url_time;
    $$ = $scope;
    present_file = '01';
    $$.animationsEnabled = true;
    ajx_fl = "php/04_bd_mrc.php";
    $$.date_to_string = date_to_string;
    $$.tri_levier = {
      col: 'Marge',
      desc: true
    };
    $$.tri_levier_regie = {
      col: 'Marge',
      desc: true
    };
    $$.tri_modifs = {
      col: 'bilan_mrg',
      desc: true
    };
    $$.tri_bid = {
      col: 'bilan_mrg',
      desc: true
    };
    $$.pourcentage = pourcentage;
    $$.sign = sign;
    $$.chk_aff_graph_lgn = false;
    $$.chk_aff_var_rel = false;
    $$.chk_aff_tableau = false;
    $$.chk_aff_gain_0 = false;
    $$.chk_aff_levier = true;
    $$.chk_aff_graph_jeux_regies = true;
    $$.chk_aff_graph_campagnes = true;
    $$.chk_aff_bilan = false;
    $$.gbd_filtree = [];
    $$.bd_glob = ['t0'];
    bd_glob_dddr = [];
    bd_tous_les_bilans = [
      {
        v_ou_p: '0',
        bd: [],
        dddp: '1954-07-28'
      }
    ];
    $$.gbd_bilan = [];
    $$.bd_levier = [];
    $$.bd_regie_jeu = [];
    $$.bd_variation = [];
    $$.bd_var_abs = [];
    $$.bd_var_rel = [];
    $$.nb_var = 4;
    $$.bd_gain_0 = [];
    $$.limit_var = 7;
    $$.var_nbj = 7;
    $$.title_variation = '7 derniers j';
    $$.rdio_dv = 'v';
    $$.show_bse_m = false;
    $$.stg_erreur = '';
    $$.TimeOffset = new Date().getTimezoneOffset() * 60 * 1000;
    $$.dte_select = "j";
    $$.TJ_exists = false;
    $$.dddr = '1954-07-28';
    $$.day_prd = 12;
    $$.dddp = '1954-07-28';
    $$.bd_empty = true;
    $$.show_menu = false;
    $$.height_blank_menu = '11em';
    $$.class_cursor = 'cursor_auto';
    cursor_waiting_for = '';
    ngClipboard = ngClipboard.ngClipboard;
    $$.show_hidden_table = false;
    $$.graph_lgn_height = '700px';
    $$.mdf = {
      bd: [],
      bd_aff: [],
      bd_reduits: [],
      flt_IdCamp: '',
      flt: {
        IdCamp: ''
      },
      show: false,
      show_one_cmp: false
    };
    $$.bid = {
      bd: [],
      bd_aff: [],
      bd_reduits: [],
      flt_IdCamp: '',
      flt: {
        IdCamp: ''
      },
      show: false
    };
    $$.logs = {
      show: false,
      chk: {
        bilan: false,
        var_abs: false,
        var_rel: false,
        table: false,
        table_flt: false,
        pie: false,
        xy: false,
        levier: false,
        gain0: false,
        cvr: false,
        crv_cmp: false,
        cvr_red: false,
        bid: false,
        bid_cmp: false,
        bid_red: false
      }
    };
    $$.board = {
      xy: false,
      bilan: false,
      debut: true,
      vu_marge_10: false,
      ancienBut: 'date _0'
    };
    $$.test = '';
    $$.bzg = {
      top: 200,
      bil: 305,
      gn0: 170,
      tab: 160,
      tab2: 50,
      xy: 200,
      jeu: 280,
      cmp: 200,
      lev: 190,
      mdf: 90,
      mdf_xy: -640,
      bid: 100,
      bid_xy: -665
    };
    ess = {
      username: 'fc'
    };
    MA = window.angular.module('app_mrc');
    $$.M_help = MA.help;
    shws = MA.shws;
    $$.show = show = function() {
      var x;
      x = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return shws.apply(null, slice.call(x).concat([present_file]));
    };
    show_err = MA.show_err;
    $$.wait_ms = wait_ms;
    $$.pgs_bar2 = MA.pgs_bar2;
    $$.backUp_db = MA.dbs;
    $$.pie_colors = MA.pie_colors;
    $$.coul = MA.coul;
    $$.coul_2 = MA.coul_2;
    mBackUp = function(n) {
      switch (n) {
        case 'variation':
          return {
            name: n,
            famille: $$.rdio_dv,
            dt1: $$.date_0,
            dt2: $$.date_2
          };
        case 'bilan':
          return {
            name: n,
            famille: $$.rdio_dv,
            dt1: 0,
            dt2: 0
          };
        case 'gain_0':
          return {
            name: n,
            famille: $$.rdio_dv,
            dt1: $$.date_0,
            dt2: $$.date_2
          };
      }
    };
    $$.pgs_bar2.start();
    $$.hide_pgs2 = function() {
      return $timeout($$.pgs_bar2.hide('xy'), 4000);
    };
    $$.show_pgs2 = function() {
      return $timeout($$.pgs_bar2.reset(20, 'xy'), 1);
    };
    $('[data-toggle="popover"]').popover();
    url_param = get_url_param('parametre');
    if (url_param === 'dv' || url_param === 'v' || url_param === 'dp' || url_param === 'p' || url_param === 'w' || url_param === 'm' || url_param === 'o' || url_param === 'at') {
      switch (url_param) {
        case 'dv':
        case 'v':
          t = 'v';
          break;
        case 'dp':
        case 'p':
          t = 'p';
          break;
        case 'w':
          t = 'w';
          break;
        case 'm':
          t = 'm';
          break;
        case 'o':
          t = 'o';
          break;
        case 'at':
          t = 'at';
      }
      $$.rdio_dv = t;
    } else if (url_param == null) {
      $$.rdio_dv = 'v';
    } else {
      $$.open_modal({
        title: "La base  - " + url_param + " -  est inexistante.",
        body: 'La base par défaut est dv',
        job: 'Dv'
      });
      $$.rdio_dv = 'v';
    }
    url_time = get_url_param('time');
    if (url_time != null) {
      u = Math.round(parseInt(url_time));
      msg = "Pour tracer une courbe je préfère disposer d'au moins deux points; merci.";
      if (u > 1) {
        $$.day_prd = $$.dddp = u;
      } else {
        $$.open_modal({
          title: "Delai graphique xy",
          body: msg,
          job: "15j"
        });
      }
    }
    url_logs = get_url_param('logs');
    if (url_logs != null) {
      if (url_logs === 'on') {
        $$.logs.show = true;
      }
    }
    get_url_bilan = function() {
      var url_bln;
      url_bln = get_url_param('bilan');
      if ((url_bln != null) && (url_bln === 'on')) {
        return true;
      } else {
        return false;
      }
    };
    $$.chk_aff_bilan = $$.board.bilan = get_url_bilan();
    $$.aff_bilan = function(yon) {
      if (yon) {
        return $$.get_bilan();
      } else {
        $$.board.bilan = false;
        return $$.board.xy = $$.chk_aff_xy = false;
      }
    };
    get_url_xy = function() {
      var url_xy;
      url_xy = get_url_param('xy');
      if ((url_xy != null) && (url_xy === 'on') && $$.chk_aff_bilan) {
        $$.board.xy = $$.chk_aff_graph_lgn = url_xy = true;
        return true;
      } else if ((url_xy != null) && (url_xy === 'on') && (!$$.chk_aff_bilan)) {
        $$.chk_aff_bilan = $$.board.bilan = true;
        $$.board.xy = $$.chk_aff_graph_lgn = url_xy = true;
        return true;
      } else {
        $$.chk_aff_graph_lgn = false;
        $$.board.xy = false;
        return false;
      }
    };
    $$.chk_aff_xy = $$.board.xy = get_url_xy();
    $$.aff_graph_lgn = function(yon) {
      var val_to_broadcast;
      if (yon && $$.board.bilan) {
        $$.board.xy = true;
        $$.pgs_bar2.reset(25000, 'xy');
        val_to_broadcast = {
          date_0: $$.date_0,
          date_2: $$.date_2,
          dddr: $$.dddr,
          dte_select: $$.dte_select,
          rdio_dv: $$.rdio_dv,
          show_bse_m: $$.show_bse_m,
          dddp: $$.dddp
        };
        $$.$broadcast('broadcast_to_xy', val_to_broadcast);
        return $$.bazinga_scroll("graph_lgn", $$.bzg.xy);
      } else {
        return $$.chk_aff_xy = $$.board.xy = false;
      }
    };
    $$.titre_menu_base = function() {
      var ref, ref1;
      if ((ref = $$.rdio_dv) === 'v' || ref === 'p') {
        return "d" + $$.rdio_dv;
      } else if ((ref1 = $$.rdio_dv) === 'w' || ref1 === 'm' || ref1 === 'o' || ref1 === 'at') {
        return $$.rdio_dv;
      }
    };
    $$.set_ifm_height = function(h, h_modif) {
      if (h_modif == null) {
        h_modif = '';
      }
      return $('#graph_lgn').css({
        height: h + h_modif
      });
    };
    $$.set_ifm_height($$.graph_lgn_height);
    $$.aff_modifs = function() {
      $$.mdf.flt.IdCamp = '';
      return $$.mdf.show = !$$.mdf.show;
    };
    $$.aff_bid = function() {
      $$.mdf.flt.IdCamp = '';
      return $$.bid.show = !$$.bid.show;
    };
    is_cmp_in_bd_glob = function(id) {
      var b, k, len, ref;
      id.toString;
      ref = $$.bd_glob;
      for (k = 0, len = ref.length; k < len; k++) {
        b = ref[k];
        if (id.toString() === b.idCamp) {
          return true;
          break;
        }
      }
      return false;
    };
    $$.is_cmp_in_bd_modifs_bid = function(id, bd) {
      var b, k, len;
      id.toString;
      for (k = 0, len = bd.length; k < len; k++) {
        b = bd[k];
        if (id.toString() === b.IdCamp.toString()) {
          return true;
          break;
        }
      }
      return false;
    };
    $$.aff_mdf_bid_loader = function(mdf, mdf_or_bid) {
      mdf.mdf_or_bid = mdf_or_bid;
      return mdf.shw_id = 'loader';
    };
    $$.aff_xy_mdf_bid = function(mdf, mdf_or_bid) {
      var fst, oth;
      if (mdf_or_bid == null) {
        mdf_or_bid = 'mdf';
      }
      mdf.shw_id = 'loader';
      mdf.mdf_or_bid = mdf_or_bid;
      if (mdf_or_bid === 'mdf') {
        fst = $$.mdf;
        oth = $$.bid;
      } else {
        fst = $$.bid;
        oth = $$.mdf;
      }
      oth.show = false;
      msg = {
        nature: 'get autre modifs',
        info: mdf,
        base: mdf_or_bid
      };
      if (oth.bd.length < 1) {
        $$.$broadcast('broadcast_to_xy', msg);
      }
      if ($$.is_cmp_in_bd_modifs_bid(mdf.IdCamp, oth.bd)) {
        oth.bd_aff = $$.bid.bd_reduits;
        oth.flt.IdCamp = mdf.IdCamp;
      }
      fst.bd_aff = fst.bd_reduits;
      if (mdf_or_bid === 'mdf') {
        $$.chk_mdf_complet = false;
      } else {
        $$.chk_bid_complet = false;
      }
      mdf.shw_id = 'btn';
      $$.show_menu = false;
      if (mdf_or_bid === 'mdf') {
        return $$.bazinga_scroll("id_modifs", $$.bzg.mdf);
      } else {
        return $$.bazinga_scroll("id_bid", $$.bzg.bid);
      }
    };
    $$.voir_mdf_ou_bid = function(mdf, mdf_or_bid) {
      var fst, oth;
      if (mdf_or_bid == null) {
        mdf_or_bid = 'mdf';
      }
      if (mdf_or_bid === 'mdf') {
        fst = $$.mdf;
        oth = $$.bid;
      } else {
        fst = $$.bid;
        oth = $$.mdf;
      }
      $$.mdf.bd_aff = $$.mdf.bd_reduits;
      $$.chk_mdf_complet = false;
      $$.bid.bd_aff = $$.bid.bd_reduits;
      $$.chk_bid_complet = false;
      fst.flt.IdCamp = mdf.IdCamp;
      $$.mdf.show_one_cmp = true;
      if (is_cmp_in_bd_glob(mdf.IdCamp)) {
        $$.filter_glob_by_id(mdf.IdCamp);
      }
      msg = {
        nature: 'modifs to display',
        info: mdf
      };
      $$.$broadcast('broadcast_to_xy', msg);
      if ($$.is_cmp_in_bd_modifs_bid(mdf.IdCamp, oth.bd)) {
        oth.show = true;
      }
      $$.bazinga_scroll("id_tableau", $$.bzg.tab2);
      return mdf.shw_id = 'no';
    };
    $$.set_flt_mdf = function(mdf) {
      $$.chk_mdf_complet = !$$.chk_mdf_complet;
      if ($$.chk_mdf_complet) {
        $$.mdf.flt.IdCamp = mdf.IdCamp;
        return $$.mdf.bd_aff = $$.mdf.bd;
      } else {
        $$.mdf.bd_aff = $$.mdf.bd_reduits;
        return $$.mdf.flt.IdCamp = '';
      }
    };
    $$.set_flt_bid = function(bid) {
      $$.chk_bid_complet = !$$.chk_bid_complet;
      if ($$.chk_bid_complet) {
        $$.bid.flt.IdCamp = bid.IdCamp;
        return $$.bid.bd_aff = $$.bid.bd;
      } else {
        $$.bid.bd_aff = $$.bid.bd_reduits;
        return $$.bid.flt.IdCamp = '';
      }
    };
    $$.aff_icon_modifs = function(val) {
      if (!typeof val === 'number') {
        return 'error';
      } else if (isNaN(val)) {
        return 'error';
      } else if (val > Number.MAX_VALUE) {
        return 'error';
      } else if (val < -Number.MAX_VALUE) {
        return 'error';
      } else if (val > 0) {
        return 'up';
      } else if (val < 0) {
        return 'down';
      } else {
        return 'error';
      }
    };
    $$.aff_pour_cent = function(val) {
      if ($$.aff_icon_modifs(val) === 'error') {
        return '';
      } else {
        return '%';
      }
    };
    $$.chk_mdf_click = function(apply_it) {
      if (apply_it == null) {
        apply_it = false;
      }
      $$.mdf.flt.IdCamp = '';
      if ($$.chk_mdf_complet) {
        $$.mdf.bd_aff = $$.mdf.bd;
      } else {
        $$.mdf.bd_aff = $$.mdf.bd_reduits;
      }
      if (apply_it) {
        return $$.$apply();
      }
    };
    $$.clic_reduce_mdf = function(mdf, chk) {
      var l, m, suite;
      l = mdf.Modif.length;
      if (l > 20) {
        l = 20;
        suite = true;
      }
      if (!chk) {
        m = mdf.Modif.slice(0, +l + 1 || 9e9);
        if (suite) {
          m += '...';
        }
      } else {
        m = mdf.Modif;
      }
      return m;
    };
    $$.clic_reduce_date = function(mdf, chk) {
      var l, m, suite;
      l = mdf.Date.length;
      if (l > 10) {
        l = 10;
        suite = true;
      }
      if (!chk) {
        m = mdf.Date.slice(0, +l + 1 || 9e9);
        if (suite) {
          m += '...';
        }
      } else {
        m = mdf.Date;
      }
      return m;
    };
    $$.clic_reduce_bid = function(mdf, chk) {
      var l, m, suite;
      l = mdf.Modif.length;
      if (l > 15) {
        l = 15;
        suite = true;
      }
      if (!chk) {
        m = mdf.Modif.slice(0, +l + 1 || 9e9);
        if (suite) {
          m += '...';
        }
      } else {
        m = mdf.Modif;
      }
      return m;
    };
    $$.clic_reduce_bid_date = function(mdf, chk) {
      var l, m, suite;
      l = mdf.Date.length;
      if (l > 10) {
        l = 10;
        suite = true;
      }
      if (!chk) {
        m = mdf.Date.slice(0, +l + 1 || 9e9);
        if (suite) {
          m += '...';
        }
      } else {
        m = mdf.Date;
      }
      return m;
    };
    $$.chk_bid_click = function(apply_it) {
      if (apply_it == null) {
        apply_it = false;
      }
      $$.bid.flt.IdCamp = '';
      if ($$.chk_bid_complet) {
        $$.bid.bd_aff = $$.bid.bd;
      } else {
        $$.bid.bd_aff = $$.bid.bd_reduits;
      }
      if (apply_it) {
        return $$.$apply();
      }
    };
    $$.fill_hidden_table = function(x) {
      return $$.h = x;
    };
    $$.w_win = function() {
      var dd, w, ww;
      ww = window;
      dd = document;
      if (ww.innerWidth) {
        w = ww.innerWidth;
      } else if (dd.documentElement && dd.documentElement.clientWidth(w = dd.documentElement.clientWidth)) {

      } else if (dd.body && dd.body.clientWidth) {
        w = dd.body.clientWidth;
      }
      return w;
    };
    $$.cal_width = function() {
      var w;
      w = $$.w_win();
      $$.tbl_w2 = ((w - 20) / 200 * 97).toFixed(0) + 'px';
      $$.tbl_w = ((w - 20) / 100 * 98).toFixed(0) + 'px';
      return $$.$apply();
    };
    window.onresize = $$.cal_width;
    $$.tbl_w = (($$.w_win() - 20) / 100 * 97).toFixed(0) + 'px';
    $$.open_modal = function(dialog, size) {
      var modalInstance;
      if (size == null) {
        size = 'sm';
      }
      modalInstance = $uibModal.open({
        animation: $scope.animationsEnabled,
        templateUrl: './php/05_modal_err.php',
        size: size,
        controller: 'ModalInstanceCtrl',
        resolve: {
          to_modal: function() {
            return dialog;
          }
        }
      });
      return modalInstance.result.then(function(from_modal) {
        if (from_modal == null) {
          from_modal = '';
        }
        return $$.set_cursor('raz_cursor');
      });
    };
    $$.$broadcast('broadcast_to_xy', 'start_xy');
    $$.maj_bd = function($$, $http, fle, v1, v2, v3, v4, $_then) {
      var response;
      if ($_then == null) {
        $_then = '';
      }
      if ($$.backUp_db.existe(mBackUp('bilan') && $$.board.bilan)) {
        $$.gbd_bilan = $$.backUp_db.get(mBackUp('bilan'));
        $$.get_bd_variation($$.var_nbj);
        return;
      }
      response = [
        '', '', {
          Date: ''
        }
      ];
      return $http.post(fle, {
        but: v1,
        date_1: v2,
        date_2: v3,
        v_ou_p: v4
      }).success(function(response, status, headers, config, v1) {
        var $_then2, but_r, e, k, len, ref, ref1, x;
        but_r = response.records[2].Date;
        if (but_r === 'dddr') {
          $$.dddr = response.records[0].date;
          return init_date($$.dddr);
        } else if (but_r !== 'bilan' && but_r !== 'variation') {
          if (but_r === 'gain_0') {
            $$.bd_gain_0 = response.records;
            handle_bd_gain_0();
            if (!$$.board.bilan) {
              return $$.$broadcast('broadcast_to_xy', 'start_xy');
            }
          } else {
            $$.bd_glob = response.records;
            if ($$.bd_glob.length < 2) {
              raz_bd_empty('Les critères de dates sont incorrects');
              return $$.change_2_dates();
            } else {
              $$.clic_tri_col('Marge');
              $$.tri = {
                col: 'Marge',
                desc: true
              };
              if (but_r === 'initial_dp') {
                bd_glob_dddr.push({
                  dv_dp: 'p',
                  bd: $$.bd_glob
                });
              }
              if (but_r === 'initial_w') {
                bd_glob_dddr.push({
                  dv_dp: 'w',
                  bd: $$.bd_glob
                });
              }
              if (but_r === 'initial_m') {
                bd_glob_dddr.push({
                  dv_dp: 'm',
                  bd: $$.bd_glob
                });
              }
              if (but_r === 'Initial') {
                bd_glob_dddr.push({
                  dv_dp: 'v',
                  bd: $$.bd_glob
                });
              }
              if (but_r === 'initial_o') {
                bd_glob_dddr.push({
                  dv_dp: 'o',
                  bd: $$.bd_glob
                });
              }
              if (but_r === 'initial_at') {
                bd_glob_dddr.push({
                  dv_dp: 'at',
                  bd: $$.bd_glob
                });
              }
              try {
                if ((ref = $$.rdio_dv) === 'v' || ref === 'p') {
                  $$.cmpr = 'd' + $$.rdio_dv;
                } else {
                  $$.cmpr = $$.rdio_dv;
                }
                if (but_r === 'initial_dp' || but_r === 'initial_w' || but_r === 'initial_m' || but_r === 'Initial' || but_r === 'initial_o' || but_r === 'initial_at') {
                  $$.bd_glob = get_bd_global_dvdp($$.rdio_dv);
                }
              } catch (error1) {
                e = error1;
                show_err("(01) :  maj_bd " + e.message, ' une erreur traitée ');
              }
              get_bd_jeux_regies_campagnes();
              return get_bd_levier();
            }
          }
        } else {
          if (but_r === 'bilan') {
            $$.gbd_bilan = response.records;
            ref1 = $$.gbd_bilan;
            for (k = 0, len = ref1.length; k < len; k++) {
              x = ref1[k];
              x.Marge = parseFloat(x.Marge);
            }
            bd_tous_les_bilans.push({
              v_ou_p: $$.rdio_dv,
              bd: $$.gbd_bilan,
              dddp: $$.dddp
            });
            $_then();
            $$.backUp_db.push(mBackUp('bilan'), $$.gbd_bilan);
            return $$.get_bd_variation($$.var_nbj);
          } else if (but_r === 'variation') {
            $$.bd_variation = response.records;
            $$.backUp_db.push(mBackUp('variation'), $$.bd_variation);
            $_then2 = function() {
              $$.pgs_bar2.hide('bilan');
              return $$.aff_graph_lgn();
            };
            handle_bd_variation($_then2);
            return $$.$broadcast('broadcast_to_xy', 'start_xy');
          }
        }
      });
    };
    get_bd_global_dvdp = function(bse) {
      var k, len;
      for (k = 0, len = bd_glob_dddr.length; k < len; k++) {
        t = bd_glob_dddr[k];
        if (t.dv_dp === bse) {
          return t.bd;
        }
      }
    };
    $$.bd_gain_0_length = function() {
      var b, i, k, len, ref;
      i = 0;
      ref = $$.bd_gain_0;
      for (k = 0, len = ref.length; k < len; k++) {
        b = ref[k];
        if (b.idCamp != null) {
          i++;
        } else {
          break;
        }
      }
      return i;
    };
    handle_bd_gain_0 = function() {
      if ($$.bd_gain_0_length() === 0) {
        $$.bd_gain_0[0].TjClic = $$.bd_gain_0[0].Marge = $$.bd_gain_0[0].idCamp = '-';
        $$.bd_gain_0[0].TjCout = $$.bd_gain_0[0].Gain = $$.bd_gain_0[0].Jeu = $$.bd_gain_0[0].Regie = '-';
        $$.bd_gain_0[0].Camp = ' Aucune ligne à gain nul ...';
      }
      return $$.backUp_db.push(mBackUp('gain_0'), $$.bd_gain_0);
    };
    handle_bd_variation = function(call_back) {
      var cb1, error, i, i1, j1, k, k1, l1, len, len1, len2, len3, len4, len5, m1, n1, n_var, o, q, ref, ref1, ref2, ref3, ref4, ref5, v, x, xid, xx, xx2, y, z;
      if (call_back == null) {
        call_back = '';
      }
      n_var = 9;
      try {
        ref = $$.bd_variation;
        for (k = 0, len = ref.length; k < len; k++) {
          y = ref[k];
          if ((y.Camp != null) && y.Camp.lastIndexOf('(') > 0) {
            y.Camp = y.Camp.slice(y.Camp.lastIndexOf("(") + 1, y.Camp.lastIndexOf(")"));
          } else {
            ref1 = ['premium', 'www', 'excluding', 'KITTY - FYBER'];
            for (o = 0, len1 = ref1.length; o < len1; o++) {
              z = ref1[o];
              if ((y.Camp != null) && y.Camp.lastIndexOf(z) > 0) {
                y.Camp = z;
              }
            }
          }
        }
        ref2 = $$.bd_variation;
        for (q = 0, len2 = ref2.length; q < len2; q++) {
          t = ref2[q];
          ref3 = ['WW, excluding live countries', 'Global', 'KITTY - FYBER'];
          for (v = 0, len3 = ref3.length; v < len3; v++) {
            z = ref3[v];
            if (t.Camp === z) {
              t.Camp = 'www';
            }
          }
        }
        ref4 = $$.bd_variation;
        for (i1 = 0, len4 = ref4.length; i1 < len4; i1++) {
          x = ref4[i1];
          xid = x.idCamp;
          x.Marge = parseFloat(x.Marge);
          x.TjClic = parseFloat(x.TjClic);
          $$.bd_glob_dvdp = get_bd_global_dvdp($$.rdio_dv);
          ref5 = $$.bd_glob_dvdp;
          for (j1 = 0, len5 = ref5.length; j1 < len5; j1++) {
            y = ref5[j1];
            if ((y.idCamp != null) && y.idCamp === xid) {
              x.Dddr_marge = parseFloat(y.Marge);
              x.Dddr_TjClic = parseFloat(y.TjClic);
              x.Var_marge = x.Dddr_marge - x.Marge;
              x.Var_clic = x.Dddr_TjClic - x.TjClic;
              xx = (x.Dddr_marge / x.Marge - 1) * 100;
              if (x.Dddr_marge >= x.Marge) {
                xx = sign(xx) * xx;
              } else {
                xx = sign(xx) * (-1) * xx;
              }
              x.Var_marge_relative = xx;
              xx2 = (x.Dddr_TjClic / x.TjClic - 1) * 100;
              if (x.Dddr_TjClic >= x.TjClic) {
                xx = sign(xx2) * xx2;
              } else {
                xx2 = sign(xx2) * (-1) * xx2;
              }
              x.Var_clic_relative = xx2;
              break;
            }
          }
          if (x.Dddr_marge == null) {
            x.Dddr_marge = 'undef';
          }
          if (x.Dddr_TjClic == null) {
            x.Dddr_marge = 'undef';
          }
        }
        $$.bd_var_abs = [];
        $$.bd_variation.sort(marge_var_abs);
        for (i = k1 = 0; k1 <= 9; i = ++k1) {
          $$.bd_var_abs.push($$.bd_variation[i]);
        }
        $$.bd_var_abs_clic = [];
        $$.bd_variation.sort(clic_var_abs);
        for (i = l1 = 0; l1 <= 9; i = ++l1) {
          $$.bd_var_abs_clic.push($$.bd_variation[i]);
        }
        $$.bd_var_rel = [];
        $$.bd_variation.sort(marge_var_rel);
        for (i = m1 = 0; m1 <= 9; i = ++m1) {
          $$.bd_var_rel.push($$.bd_variation[i]);
        }
        $$.bd_var_rel_clic = [];
        $$.bd_variation.sort(clic_var_rel);
        for (i = n1 = 0; n1 <= 9; i = ++n1) {
          $$.bd_var_rel_clic.push($$.bd_variation[i]);
        }
        cb1 = function() {
          return $$.$broadcast('broadcast_to_xy', 'bd var ok');
        };
        return setTimeout(cb1);
      } catch (error1) {
        error = error1;
        return show(' :  (01)  : handle_bd_variation ', 'fc, Erreur traitée : ' + error.message);
      } finally {
        $$.set_cursor('raz_cursor');
        if (typeof call_back === "function") {
          $timeout(call_back, 3000);
        }
      }
    };
    $$.maj_bd_2 = function(dte) {
      $$.dates = date_to_string(dte);
      $$.maj_bd($$, $http, ajx_fl, "date", date_to_string(dte), date_to_string(dte), $$.rdio_dv);
      if ($$.backUp_db.existe(mBackUp('gain_0'))) {
        $$.bd_gain_0 = $$.backUp_db.get(mBackUp('gain_0'));
      } else {
        $$.maj_bd($$, $http, ajx_fl, "gain_0", date_to_string(dte), date_to_string(dte), $$.rdio_dv);
      }
      return get_bd_levier();
    };
    $$.change_2_dates = function() {
      var map;
      $$.dates = " du  " + (date_to_string($$.date_0)) + "  au  " + (date_to_string($$.date_2));
      $$.board.ancienBut = 'date_0_et_2';
      $$.maj_bd($$, $http, ajx_fl, 'periode', date_to_string($$.date_0), date_to_string($$.date_2), $$.rdio_dv);
      map = {
        name: 'gain_0',
        famille: $$.rdio_dv,
        dt1: $$.date_0,
        dt2: $$.date_2
      };
      if ($$.backUp_db.existe(mBackUp('gain_0'))) {
        $$.bd_gain_0 = $$.backUp_db.get(mBackUp('gain_0'));
      } else {
        $$.maj_bd($$, $http, ajx_fl, "gain_0", date_to_string($$.date_0), date_to_string($$.date_2), $$.rdio_dv);
      }
      get_bd_levier();
      return broadcast_lower();
    };
    cb = function() {
      var foo;
      return foo = 0;
    };
    smoothScroll.init({
      speed: 1954,
      easing: 'easeInOutCubic',
      offset: 0,
      updateURL: true,
      callback: cb
    });
    $$.bazinga_scroll = function(id, off_set) {
      var options, toggle;
      if (off_set == null) {
        off_set = 0;
      }
      toggle = document.querySelector('#toggle');
      options = {
        speed: 1954 - 954,
        easing: 'easeInCubic',
        offset: off_set
      };
      return smoothScroll.animateScroll('#' + id, toggle, options);
    };
    $$.change_scope = function(is_on, id, offset) {
      if (is_on) {
        return $$.bazinga_scroll(id, offset);
      }
    };
    $$.bazinga_scroll('id_top', $$.bzg.top);
    $$.bazinga_tableau = function() {
      return $$.change_scope($$.chk_aff_tableau, 'id_tableau', $$.bzg.tab);
    };
    $$.dte_n_jours_avant = function(dte, n) {
      var d2;
      if (n == null) {
        n = 15;
      }
      d2 = new Date(dte.getFullYear(), dte.getMonth(), dte.getDate() - n, 1, 0, 1, 1);
      return date_to_string(d2);
    };
    $$.hier = function(dte) {
      return $$.dte_n_jours_avant(dte, 1);
    };
    $$.change_begining_prd = function(n_days) {
      $$.dddp = $$.dte_n_jours_avant(new Date($$.dddr), n_days);
      return broadcast_lower();
    };
    init_date = function(d) {
      window.top.date_0 = $$.date_0 = $$.date_2 = new Date(d);
      $$.dddp = $$.dte_n_jours_avant(new Date($$.dddr), $$.day_prd);
      switch ($$.rdio_dv) {
        case 'v':
          $$.maj_bd($$, $http, ajx_fl, 'Initial', d, d, $$.rdio_dv);
          break;
        case 'p':
          $$.maj_bd($$, $http, ajx_fl, 'initial_dp', d, d, $$.rdio_dv);
          break;
        case 'w':
          $$.maj_bd($$, $http, ajx_fl, 'initial_w', d, d, $$.rdio_dv);
          break;
        case 'm':
          $$.maj_bd($$, $http, ajx_fl, 'initial_m', d, d, $$.rdio_dv);
          break;
        case 'o':
          $$.maj_bd($$, $http, ajx_fl, 'initial_o', d, d, $$.rdio_dv);
          break;
        case 'at':
          $$.maj_bd($$, $http, ajx_fl, 'initial_at', d, d, $$.rdio_dv);
      }
      $$.maj_bd($$, $http, ajx_fl, 'gain_0', d, d, $$.rdio_dv);
      $$.get_bilan();
      broadcast_lower('pie only');
      return $$.dates = d;
    };
    dte_last_report = function() {
      return new Date(new Date().getTime() - 31 * 3600000 + 1 * $$.TimeOffset);
    };
    window.top.date_0 = $$.date_2 = $$.date_0 = dte_last_report();
    stg = new Date(new Date().getTime() - 31 * 3600 * 1000 + 0 * $$.TimeOffset).toISOString().slice(0, 10);
    $$.dates = stg;
    $$.$on('emit_from_pie_to_parent', function(event, args) {
      var ok;
      ok = date_is_ok(args.date_0) && date_is_ok(args.date_2);
      if (ok) {
        $$.date_0 = args.date_0;
        $$.date_2 = args.date_2;
        $$.rdio_dv = args.rdio_dv;
        $$.dte_select = args.dte_select;
        $$.$broadcast('broadcast_to_xy', $$.rdio_dv);
        $$.change_2_dates();
        return $$.get_bilan();
      } else {
        return raz_bd_empty('Erreur de date', 'Une des  dates requise pour le graphique des pies est postérieure à celle de la dernière extraction.');
      }
    });
    broadcast_lower = function(info) {
      var val_to_broadcast;
      if (info == null) {
        info = '';
      }
      val_to_broadcast = {
        date_0: $$.date_0,
        date_2: $$.date_2,
        dddr: $$.dddr,
        dte_select: $$.dte_select,
        rdio_dv: $$.rdio_dv,
        show_bse_m: $$.show_bse_m,
        dddp: $$.dddp
      };
      $$.$broadcast('broadcast_from_parent_to_pie', val_to_broadcast);
      if (!info === 'pie only') {
        return $$.$broadcast('broadcast_to_xy', val_to_broadcast);
      }
    };
    date_is_ok = function(dte) {
      var dtemp;
      dtemp = date_to_string(new Date(dte));
      return dtemp <= $$.dddr;
    };
    $$.change_D0 = function() {
      if (date_is_ok($$.date_0)) {
        $$.dte_select = '';
        broadcast_lower();
        $$.board.ancienBut = 'date_0';
        return $$.maj_bd_2(date_to_string($$.date_0));
      } else {
        return raz_bd_empty('Erreur de date', 'La date requise est postérieure à celle de la dernière extraction.');
      }
    };
    $$.change_D2 = function() {
      if (date_is_ok($$.date_2)) {
        $$.dte_select = '';
        broadcast_lower();
        $$.board.ancienBut = 'date_2';
        return $$.maj_bd_2(date_to_string($$.date_2));
      } else {
        return raz_bd_empty('Erreur de date', 'La date requise est postérieure à celle de la dernière extraction.');
      }
    };
    $$.menu_on_off = function(visible) {
      $$.show_menu = visible === 'visible';
      if (visible === 'visible') {
        return $$.height_blank_menu = 'height_blank_menu_1';
      } else {
        return $$.height_blank_menu = 'height_blank_menu_2';
      }
    };
    $$.menu_on_off2 = function() {
      if ($$.show_menu) {
        return $$.menu_on_off('hidden');
      } else {
        return $$.menu_on_off('visible');
      }
    };
    $$.maj_bd($$, $http, ajx_fl, 'dddr', '', '', '');
    $$.bd_glob = get_bd_global_dvdp($$.rdio_dv);
    $$.clic_tri_col = function(col) {
      var k, len, ref, z;
      if (col !== 'Regie' && col !== 'Jeu' && col !== 'Camp' && col !== 'renta') {
        ref = $$.bd_glob;
        for (k = 0, len = ref.length; k < len; k++) {
          z = ref[k];
          z[col] = parseFloat(z[col]);
        }
      }
      if ($$.tri.col !== col) {
        return $$.tri.col = col;
      } else {
        return $$.tri.desc = !$$.tri.desc;
      }
    };
    $$.clic_tri_col_simple = function(col, sens) {
      var k, len, ref, z;
      if (sens == null) {
        sens = 'up';
      }
      if (col !== 'Regie' && col !== 'Jeu' && col !== 'Camp') {
        ref = $$.bd_glob;
        for (k = 0, len = ref.length; k < len; k++) {
          z = ref[k];
          z[col] = parseFloat(z[col]);
        }
      }
      if ($$.tri.col !== col) {
        $$.tri.col = col;
      }
      if (sens === 'up') {
        return $$.tri.desc = true;
      } else {
        return $$.tri.desc = false;
      }
    };
    $$.clic_tri_modifs = function(col, sens) {
      var k, len, ref, z;
      if (sens == null) {
        sens = 'up';
      }
      if (col !== 'Date' && col !== 'Regie' && col !== 'Jeu' && col !== 'Camp') {
        ref = $$.mdf.bd;
        for (k = 0, len = ref.length; k < len; k++) {
          z = ref[k];
          z[col] = parseFloat(z[col]);
        }
      }
      if ($$.tri_modifs.col !== col) {
        $$.tri_modifs.col = col;
      }
      if (sens === 'up') {
        return $$.tri_modifs.desc = true;
      } else {
        return $$.tri_modifs.desc = false;
      }
    };
    $$.clic_tri_bid = function(col, sens) {
      var k, len, ref, z;
      if (sens == null) {
        sens = 'up';
      }
      if (col !== 'Date' && col !== 'Regie' && col !== 'Jeu' && col !== 'Camp') {
        ref = $$.bid.bd;
        for (k = 0, len = ref.length; k < len; k++) {
          z = ref[k];
          z[col] = parseFloat(z[col]);
        }
      }
      if ($$.tri_bid.col !== col) {
        $$.tri_bid.col = col;
      }
      if (sens === 'up') {
        return $$.tri_bid.desc = true;
      } else {
        return $$.tri_bid.desc = false;
      }
    };
    $$.clic_tri_lev = function(col) {
      if ($$.tri_levier.col !== col) {
        $$.tri_levier.col = col;
      } else {
        $$.tri_levier.desc = !$$.tri_levier.desc;
      }
      $$.get_bd_regie_jeu($$.bd_levier[0].Jeu);
      return $$.change_scope($$.chk_aff_levier, 'id_levier', $$.bzg.lev - 120);
    };
    $$.clic_tri_levier_regie = function(col) {
      if ($$.tri_levier_regie.col !== col) {
        return $$.tri_levier_regie.col = col;
      } else {
        return $$.tri_levier_regie.desc = !$$.tri_levier_regie.desc;
      }
    };
    $$.get_bd_regie_jeu = function(j) {
      var b0, b1, bb, c, k, len, m, p, r, rta;
      b0 = $$.bd_glob.where({
        Jeu: j
      });
      b1 = [];
      for (k = 0, len = b0.length; k < len; k++) {
        bb = b0[k];
        c = parseFloat(bb.TjCout);
        m = parseFloat(bb.Marge);
        p = bb.Camp;
        r = bb.Regie;
        rta = c !== 0 ? -m / c * 1.2 : sign(m) * Number.MAX_VALUE;
        b1.push({
          Jeu: j,
          Regie: r,
          Marge: m,
          Cout: c,
          Renta: rta,
          Camp: p
        });
      }
      return $$.bd_regie_jeu = b1;
    };
    $$.change_select_tab = function(type, value) {
      if ($$.rdio_action === '-10') {
        $$.set_cursor('wait');
        partial_raz();
        $$.filtre[type] = value;
        $$.rdio_action = '';
      }
      return $$.rdio_action = '';
    };
    $$.sum_col = function(col) {
      var k, len, ref, s, y;
      try {
        s = 0;
        ref = $$.gbd_filtree;
        for (k = 0, len = ref.length; k < len; k++) {
          y = ref[k];
          s += parseFloat(y[col]);
        }
        return s;
      } catch (error1) {}
    };
    $$.sum_global = function(col) {
      var k, len, ref, s, y;
      s = 0;
      try {
        ref = $$.bd_glob;
        for (k = 0, len = ref.length; k < len; k++) {
          y = ref[k];
          s += parseFloat(y[col]);
        }
        return s.toFixed(0);
      } catch (error1) {}
    };
    partial_raz = function() {
      $$.fMarge = $$.fTjCPM = $$.fGain = $$.fRenta = $$.fJeu = '';
      $$.filtre = {
        Jeu: '',
        Regie: '',
        Camp: ''
      };
      return $$.clic_tri_col('Marge');
    };
    $$.raz_filtre = function() {
      partial_raz();
      $$.dte_select = "j";
      $$.date_0 = $$.date_2 = new Date($$.dddr);
      $$.menu_on_off('visible');
      broadcast_lower();
      return $$.mdf.show_one_cmp = false;
    };
    $$.cvr_cpm = $$.cvr_inf_1 = $$.change_700 = $$.change_70 = $$.change_raz = $$.change_0 = function() {
      return $$.raz_filtre();
    };
    $$.change_R = $$.change_T = $$.change_M = $$.change_G = function() {
      return $$.rdio_action = '';
    };
    $$.change_tjcpm5 = function(max_tjcpm) {
      var j7;
      if (max_tjcpm == null) {
        max_tjcpm = 5;
      }
      j7 = new Date(new Date($$.dddr).getTime() - 6 * 24 * 3600000);
      $$.date_0 = new Date($$.dddr);
      $$.date_2 = j7;
      $$.dates = " du  " + (date_to_string($$.date_0)) + "  au  " + (date_to_string($$.date_2));
      $$.board.ancienBut = 'date_0_et_2';
      $$.maj_bd($$, $http, ajx_fl, 'periode', date_to_string($$.date_0), date_to_string($$.date_2), $$.rdio_dv);
      $$.fTjCPM = max_tjcpm;
      $$.filtre = {
        Regie: 'TJ',
        Jeu: '',
        Camp: ''
      };
      $$.fMarge = $$.fGain = $$.fRenta = '';
      $$.clic_tri_col('Marge');
      $$.dte_select = "j7";
      $$.chk_aff_tableau = true;
      $$.bazinga_scroll('id_tableau', $$.bzg.tab);
      return broadcast_lower();
    };
    $$.$watch("filtre.Regie", function(nw, old) {
      if (nw !== old) {
        $$.class_cursor = 'cursor_wait';
        return cursor_waiting_for = 'regie';
      }
    });
    $$.$watch("filtre.Jeu", function(nw, old) {
      if (nw !== old) {
        $$.class_cursor = 'cursor_wait';
        return cursor_waiting_for = 'regie';
      }
    });
    $$.$watch("filtre.Camp", function(nw, old) {
      if (nw !== old) {
        $$.class_cursor = 'cursor_wait';
        return cursor_waiting_for = 'regie';
      }
    });
    idx_lst = 0;
    $$.when_last = function(lst) {
      if (cursor_waiting_for === 'filtre' || cursor_waiting_for === 'regie') {
        idx_lst++;
      }
      if (idx_lst > 6 && cursor_waiting_for === 'filtre') {
        $$.set_cursor('raz_cursor');
        idx_lst = 0;
      }
      if (idx_lst > 2 && cursor_waiting_for === 'regie') {
        $$.set_cursor('raz_cursor');
        return idx_lst = 0;
      }
    };
    $$.set_cursor = function(cr, call_back) {
      var set_end_filtre;
      if (call_back == null) {
        call_back = '';
      }
      set_end_filtre = function() {
        return $$.set_cursor('raz_cursor');
      };
      if (cr === 'wait' || cr === 'dte' || cr === 'mois') {
        $$.class_cursor = 'cursor_wait';
        cursor_waiting_for = cr;
        $timeout(set_end_filtre, 6500);
        return 0;
      }
      if (cr === 'filtre' && cursor_waiting_for === '') {
        $$.class_cursor = 'cursor_wait';
        cursor_waiting_for = cr;
        $timeout(set_end_filtre, 4000);
        return 0;
      }
      if (cr === 'bilan' && !$$.chk_aff_bilan) {
        $$.class_cursor = 'cursor_wait';
        cursor_waiting_for = cr;
        return 0;
      }
      if (cr === 'raz_cursor') {
        $$.class_cursor = 'cursor_auto';
        cursor_waiting_for = '';
        return 0;
      }
      if (cr === 'auto' && cursor_waiting_for === 'wait') {
        $$.class_cursor = 'cursor_auto';
        cursor_waiting_for = '';
        return 0;
      }
      if (cr === 'fin_mois' && cursor_waiting_for === 'mois') {
        $$.class_cursor = 'cursor_auto';
        cursor_waiting_for = '';
        return 0;
      }
    };
    $$.get_bilan = function() {
      var $_then;
      $$.pgs_bar2.reset(20, 'bilan');
      $_then = function() {
        return $$.board.bilan = true;
      };
      if ($$.chk_aff_bilan) {
        return $$.maj_bd($$, $http, ajx_fl, 'bilan', $$.dddr, $$.dddp, $$.rdio_dv, $_then);
      }
    };

    /*changement dv dp */
    $$.change_dv = function() {
      $$.show_menu = false;
      $$.pgs_bar2.reset(40, 'pie');
      $$.chk_aff_bilan = $$.chk_aff_xy = $$.chk_aff_tableau = false;
      $$.board.xy = $$.board.bilan = false;
      $$.chk_aff_bilan = $$.chk_aff_graph_lgn = false;
      $$.rdio_action = '700';
      $$.board.vu_marge_10 = false;
      $$.bd_glob = [];
      switch ($$.rdio_dv) {
        case 'v':
          $$.maj_bd($$, $http, ajx_fl, 'Initial', $$.dddr, $$.dddr, $$.rdio_dv);
          break;
        case 'p':
          $$.maj_bd($$, $http, ajx_fl, 'initial_dp', $$.dddr, $$.dddr, $$.rdio_dv);
          break;
        case 'w':
          $$.maj_bd($$, $http, ajx_fl, 'initial_w', $$.dddr, $$.dddr, $$.rdio_dv);
          break;
        case 'm':
          $$.maj_bd($$, $http, ajx_fl, 'initial_m', $$.dddr, $$.dddr, $$.rdio_dv);
          break;
        case 'o':
          $$.maj_bd($$, $http, ajx_fl, 'initial_o', $$.dddr, $$.dddr, $$.rdio_dv);
          break;
        case 'at':
          $$.maj_bd($$, $http, ajx_fl, 'initial_at', $$.dddr, $$.dddr, $$.rdio_dv);
      }
      broadcast_lower();
      $$.board.debut = true;
      $$.get_bilan();
      $$.filtre = {
        Jeu: '',
        Regie: '',
        Camp: ''
      };
      $$.bid.show = $$.mdf.show = false;
      $$.mdf.bd_aff = $$.mdf.bd_reduits = $$.mdf.bd = [];
      $$.bid.bd_aff = $$.bid.bd_reduits = $$.bid.bd = [];
      $$.bid.flt.IdCamp = $$.mdf.flt.IdCamp = '';
      $$.mdf.bd_aff = $$.mdf.bd_reduits;
      $$.bid.bd_aff = $$.bid.bd_reduits;
      $$.chk_mdf_complet = $$.chk_bid_complet = false;
      $$.mdf.show_one_cmp = false;
      switch ($$.board.ancienBut) {
        case 'date_0':
          $$.change_2_dates();
          break;
        case 'date_2':
          $$.change_2_dates();
          break;
        default:
          $$.change_2_dates();
      }
      return $$.bazinga_scroll('id_top');
    };
    $$.change_dte_select = function(dte) {
      var d, hier, j30, j7, today;
      $$.set_cursor('wait');
      $$.pgs_bar2.reset(20, 'bilan');
      switch (dte) {
        case "j":
        case '':
          today = new Date($$.dddr);
          $$.date_0 = $$.date_2 = today;
          $$.change_bd_variation(date_to_string(new Date(new Date($$.dddr).getTime() - 6 * 24 * 3600000)), 7);
          break;
        case "j-1":
          hier = new Date(new Date($$.dddr).getTime() - 24 * 3600000);
          $$.date_0 = $$.date_2 = hier;
          $$.change_bd_variation(2, 2);
          break;
        case "j7":
          j7 = new Date(new Date($$.dddr).getTime() - 8 * 24 * 3600000);
          $$.date_0 = new Date($$.dddr);
          $$.date_2 = j7;
          $$.change_bd_variation(date_to_string($$.date_2), 7);
          break;
        case "j30":
          j30 = new Date(new Date($$.dddr).getTime() - 31 * 24 * 3600000);
          $$.date_0 = new Date($$.dddr);
          $$.date_2 = j30;
          $$.change_bd_variation(date_to_string($$.date_2), 30);
          break;
        case "mois":
          $$.date_0 = d = new Date($$.dddr);
          $$.date_2 = new Date(d.getFullYear(), d.getMonth(), 1, 0, 0, 1, 1);
          $$.change_bd_variation(date_to_string($$.date_2), 'mois');
          break;
        case "mois-1":
          d = new Date($$.dddr);
          $$.date_0 = new Date(d.getFullYear(), d.getMonth(), 0, 1, 0, 1, 1);
          $$.date_2 = new Date(d.getFullYear(), d.getMonth() - 1, 1, 1, 0, 1, 1);
          $$.change_bd_variation(date_to_string($$.date_2), 'mois-1');
          break;
        case "tout":
          $$.date_0 = new Date($$.dddr);
          d = new Date(new Date('2010-01-01').getTime());
          $$.date_2 = d;
          $$.change_bd_variation(date_to_string($$.date_2), 'tout');
      }
      $$.change_2_dates();
      return broadcast_lower();
    };
    $$.filtre = {
      Jeu: '',
      Regie: '',
      Camp: ''
    };
    $$.fMarge = $$.fTjCPM = $$.fRenta = $$.fGain = '';
    $$.rdio_action = "700";
    $$.tri = {
      col: 'Marge',
      desc: true
    };
    $$.tri_levier = {
      col: 'Marge',
      desc: true
    };
    $$.titre = '';
    $$.Gain_sup = function(x) {
      return x.Gain > $$.fGain;
    };
    $$.Renta_inf = function(x) {
      if ($$.fRenta === '') {
        return true;
      } else {
        if (1 * x.TjCout === 0) {
          return false;
        } else {
          return -x.Marge / x.TjCout * 1.2 <= $$.fRenta;
        }
      }
    };
    $$.TjCPM_inf = function(x) {
      if ($$.fTjCPM === '') {
        return true;
      } else {
        return x.TjCPM < $$.fTjCPM;
      }
    };
    $$.is_id = function(x) {
      if (!$$.mdf.show_one_cmp) {
        return true;
      }
      return parseFloat(x.idCamp) === parseFloat($$.mdf.flt_IdCamp);
    };
    marge_inf_10_exists = function(bd) {
      var k, len, y;
      for (k = 0, len = bd.length; k < len; k++) {
        y = bd[k];
        if (parseFloat(y.Marge) < -10) {
          return true;
        }
      }
      return false;
    };
    $$.Marge_sup = function(x) {
      var k, len, len1, len2, m, m_inf10, mt, o, q, ref, ref1, ref2, ref3, xmax, y;
      xmax = m = mt = 0;
      ref = $$.bd_glob;
      for (k = 0, len = ref.length; k < len; k++) {
        y = ref[k];
        mt += parseFloat(y['Marge']);
      }
      ref1 = $$.bd_glob;
      for (o = 0, len1 = ref1.length; o < len1; o++) {
        y = ref1[o];
        xmax = parseFloat(y['Marge']);
        if (!(xmax > 0 && m < 0.7 * mt)) {
          break;
        }
        m += xmax;
      }
      m_inf10 = false;
      if ($$.chk_aff_tableau === false && !$$.board.vu_marge_10) {
        ref2 = $$.bd_glob;
        for (q = 0, len2 = ref2.length; q < len2; q++) {
          y = ref2[q];
          if (parseFloat(y.Marge) < -10) {
            m_inf10 = true;
            break;
          }
        }
        if (m_inf10) {
          $$.rdio_action = "-10";
          $$.chk_aff_tableau = true;
          $$.board.vu_marge_10 = true;
        } else {
          $$.rdio_action = '700';
        }
      }
      switch ($$.rdio_action) {
        case "cvr_1":
          return parseFloat(x.Transfo) / parseFloat(x.TjClic) * 100 < 1;
        case "cvr_1_&_cpm_5":
          return (parseFloat(x.Transfo) / parseFloat(x.TjClic) * 100 < 1) && (parseFloat(x.TjCPM) < 5);
        case "70":
          return x.Marge > xmax;
        case "-10":
          return x.Marge < -10;
        case "0":
          return x.Marge < 0;
        case "700":
          return !((xmax >= (ref3 = parseFloat(x.Marge)) && ref3 > 0));
        default:
          if ($$.fMarge === '') {
            xmax = -1e300;
          } else {
            xmax = $$.fMarge;
          }
          return 1 * x.Marge > xmax;
      }
    };
    $$.change_marge_renta = function(m_min, r_max) {
      var bdl;
      if (m_min == null) {
        m_min = 100;
      }
      if (r_max == null) {
        r_max = 2;
      }
      bdl = [];
      $$.fTjCPM = $$.fGain = $$.fJeu = '';
      $$.filtre = {
        Jeu: '',
        Regie: '',
        Camp: ''
      };
      $$.fMarge = -2e308;
      $$.clic_tri_col('Marge');
      $$.fRenta = 2;
      $$.fMarge = m_min;
      $$.chk_aff_tableau = true;
      return $$.bazinga_scroll('id_tableau', $$.bzg.tab);
    };
    $$.i_var = function() {
      switch ($$.dte_select) {
        case 'j-1':
          return 1;
        case 'j7':
          return 2;
        case 'j30':
          return 3;
        case 'mois':
          return 4;
        case 'mois-1':
          return 5;
        case 'tout':
          return 6;
        default:
          return 2;
      }
    };
    set_title_variation = function(laps) {
      var ttl;
      switch (laps) {
        case 2:
          ttl = '2 derniers j';
          break;
        case 7:
          ttl = '7 derniers j';
          break;
        case 30:
          ttl = '30 derniers j';
          break;
        case 'mois':
          ttl = 'mois en cours';
          break;
        case 'mois-1':
          ttl = 'mois précédent';
          break;
        case 'tout':
          ttl = 'prd en jours';
          break;
        default:
          ttl = '7 derniers j';
      }
      return ttl;
    };
    $$.get_bd_variation = function(nbj) {
      var dte;
      if (nbj == null) {
        nbj = 7;
      }
      if (typeof nbj === 'number') {
        dte = date_to_string(new Date(new Date($$.dddr).getTime() - (nbj - 1) * 24 * 3600000));
      } else {
        dte = nbj;
      }
      $$.bd_variation = [];
      if ($$.backUp_db.existe(mBackUp('variation'))) {
        $$.bd_variation = $$.backUp_db.get(mBackUp('variation'));
        $$.pgs_bar2.hide('bilan');
        return $$.set_cursor('raz_cursor');
      } else {
        return $$.maj_bd($$, $http, ajx_fl, 'variation', $$.dddr, dte, $$.rdio_dv);
      }
    };
    $$.change_bd_variation = function(nbj, periode) {
      if (nbj == null) {
        nbj = 7;
      }
      if (periode == null) {
        periode = 7;
      }
      $$.get_bd_variation(nbj);
      handle_bd_variation();
      return $$.title_variation = set_title_variation(periode);
    };
    $$.var_2_glob = function(cmp) {
      $$.filtre = {
        Regie: cmp.Regie,
        Jeu: cmp.Jeu,
        Camp: cmp.Camp
      };

      /* raz des filtres inutiles */
      $$.fMarge = $$.fGain = $$.fRenta = '';
      $$.chk_aff_tableau = true;
      $$.rdio_action = '';
      return $$.bazinga_scroll('id_tableau', $$.bzg.tab2);
    };
    $$.filter_glob_by_id = function(id) {
      $$.filtre = {
        Regie: '',
        Jeu: '',
        Camp: ''
      };
      $$.fMarge = $$.fRenta = '';
      $$.mdf.flt_IdCamp = id;
      $$.chk_aff_tableau = true;
      $$.fGain = $$.rdio_action = '';
      return $$.bazinga_scroll('id_tableau', $$.bzg.tab2);
    };
    get_bd_levier = function(bd) {
      var bdl, d, e, foo, j, jx, k, len, ref;
      if (bd == null) {
        bd = $$.bd_glob;
      }
      $$.bd_levier = bdl = [];
      jx = [];
      if (bd != null) {
        for (k = 0, len = bd.length; k < len; k++) {
          d = bd[k];
          if (ref = d.Jeu, indexOf.call(jx, ref) < 0) {
            bdl.push({
              Jeu: d.Jeu,
              Cout: parseFloat(d.TjCout),
              Marge: parseFloat(d.Marge),
              Renta: parseFloat(d.Renta)
            });
            jx.push(d.Jeu);
          } else {
            j = (bdl.where({
              Jeu: d.Jeu
            }))[0];
            j.Cout += parseFloat(d.TjCout);
            j.Marge += parseFloat(d.Marge);
            if (j.cout === 0) {
              j.Renta = sign(j.Marge) * Number.MAX_VALUE;
            } else {
              j.Renta = -j.Marge / j.Cout * 1.2;
            }
          }
        }
        $$.bd_levier.sort(function(a, b) {
          return a.Marge < b.Marge;
        });
        $$.bd_levier = bdl;
      }
      try {
        return $$.get_bd_regie_jeu($$.bd_levier[0].Jeu);
      } catch (error1) {
        e = error1;
        return foo = 0;
      } finally {
        $$.set_cursor('end_dte');
      }
    };
    get_bd_jeux_regies_campagnes = function() {
      var e, i1, k, len, len1, len2, len3, len4, o, q, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, results, tc, tj, tr, v, y, z;
      try {
        $$.bd_jeux = [];
        tj = [];
        ref = $$.bd_glob;
        for (k = 0, len = ref.length; k < len; k++) {
          y = ref[k];
          if (!(ref1 = y.Jeu, indexOf.call(tj, ref1) >= 0)) {
            tj.push(y.Jeu);
            $$.bd_jeux.push({
              name: y.Jeu,
              value: y.Jeu
            });
          }
        }
        $$.bd_regies = [];
        tr = [];
        ref2 = $$.bd_glob;
        for (o = 0, len1 = ref2.length; o < len1; o++) {
          y = ref2[o];
          if (!(ref3 = y.Regie, indexOf.call(tr, ref3) >= 0)) {
            tr.push(y.Regie);
            $$.bd_regies.push({
              name: y.Regie,
              value: y.Regie
            });
          }
        }
        $$.TJ_exists = (indexOf.call(tr, 'TJ') >= 0);
        $$.bd_camp = [];
        tc = [];
        ref4 = $$.bd_glob;
        results = [];
        for (q = 0, len2 = ref4.length; q < len2; q++) {
          y = ref4[q];
          if ((y.Camp != null) && y.Camp.lastIndexOf('(') > 0) {
            y.Camp = y.Camp.slice(y.Camp.lastIndexOf("(") + 1, y.Camp.lastIndexOf(")"));
          } else {
            ref5 = ['premium', 'www', 'excluding', 'KITTY - FYBER'];
            for (v = 0, len3 = ref5.length; v < len3; v++) {
              z = ref5[v];
              if ((y.Camp != null) && y.Camp.lastIndexOf(z) > 0) {
                y.Camp = z;
              }
            }
          }
          ref6 = ['WW, excluding live countries', 'Global', 'KITTY - FYBER'];
          for (i1 = 0, len4 = ref6.length; i1 < len4; i1++) {
            z = ref6[i1];
            if (y.Camp === z) {
              y.Camp = 'www';
            }
          }
          if (!(ref7 = y.Camp, indexOf.call(tc, ref7) >= 0)) {
            tc.push(y.Camp);
            results.push($$.bd_camp.push({
              name: y.Camp,
              value: y.Camp
            }));
          } else {
            results.push(void 0);
          }
        }
        return results;
      } catch (error1) {
        e = error1;
        if ($$.bd_glob == null) {
          show('(01) : get_bd_jeu, 01, erreur traitée');
        } else {
          return show('(01) : get_bd_j', 'erreur inconnue');
        }
      }
    };
    $$.format_n = function(a, t) {
      if (t == null) {
        t = 0;
      }
      u = parseFloat(parseFloat(a).toFixed(t));
      if ((a === 2e308 || a === (-2e308)) || isNaN(a)) {
        return '';
      }
      return u.toLocaleString();
    };
    rac = new Raccourcis;
    $$.kb_event = function(e) {
      var all_on_off, todo;
      all_on_off = function(on_off) {
        $$.chk_aff_bilan = on_off;
        $$.chk_aff_graph_jeux_regies = on_off;
        $$.chk_aff_graph_campagnes = on_off;
        $$.chk_aff_graph_campagnes = on_off;
        $$.chk_aff_tableau = on_off;
        $$.chk_aff_graph_lgn = on_off;
        $$.chk_aff_levier = on_off;
        return $$.chk_aff_gain_0 = on_off;
      };
      rac.get_event(e);
      if (rac.keydown) {
        return;
      }
      todo = function() {
        if (rac.short) {
          return 'flip';
        } else {
          all_on_off(false);
          return 'on';
        }
      };
      switch (e.keyCode) {
        case 66:
          $$.chk_aff_bilan = rac.flip($$.chk_aff_bilan, todo());
          if ($$.chk_aff_bilan) {
            $$.bazinga_scroll('id_bilan', $$.bzg.bil);
          }
          break;
        case 82:
          $$.chk_aff_graph_jeux_regies = rac.flip($$.chk_aff_graph_jeux_regies, todo());
          if (!$$.chk_aff_graph_jeux_regies) {
            $$.bazinga_scroll('id_aff_graph_jeux_regies', $$.bzg.jeu);
          }
          break;
        case 67:
          $$.chk_aff_graph_campagnes = rac.flip($$.chk_aff_graph_campagnes, todo());
          if (!$$.chk_aff_graph_campagnes) {
            $$.bazinga_scroll('id_aff_graph_campagnes', $$.bzg.cmp);
          }
          break;
        case 71:
          $$.chk_aff_gain_0 = rac.flip($$.chk_aff_gain_0, todo());
          if (!$$.chk_aff_gain_0) {
            $$.bazinga_scroll('id_gain_0', $$.bzg.gn0);
          }
          break;
        case 84:
          $$.chk_aff_tableau = rac.flip($$.chk_aff_tableau, todo());
          if ($$.chk_aff_tableau) {
            $$.bazinga_scroll('id_tableau', $$.bzg.tab2);
            $$.menu_on_off('visible');
          }
          break;
        case 88:
        case 89:
          $$.chk_aff_graph_lgn = rac.flip($$.chk_aff_graph_lgn, todo());
          if ($$.chk_aff_graph_lgn) {
            $$.bazinga_scroll('graph_lgn', $$.bzg.xy);
          }
          break;
        case 76:
          $$.chk_aff_levier = rac.flip($$.chk_aff_levier, todo());
          if ($$.chk_aff_levier) {
            $$.bazinga_scroll('id_fin', 55);
          }
          break;
        case 38:
          $$.menu_on_off('hidden');
          break;
        case 40:
          $$.menu_on_off('visible');
          break;
        case 65:
          all_on_off(true);
          break;
        case 78:
          all_on_off(false);
          break;
        case 33:
          $$.rdio_action = 'raz';
          $$.raz_filtre();
          break;
        case 74:
          $$.dte_select = 'j';
          $$.change_dte_select('j');
          break;
        case 83:
          $$.dte_select = 'j7';
          $$.change_dte_select('j7');
          break;
        case 77:
          $$.dte_select = 'mois';
          $$.change_dte_select('mois');
          break;
        case 69:
          $$.dte_select = 'tout';
          $$.change_dte_select('tout');
          break;
        case 86:
          $$.rdio_dv = 'v';
          $$.change_dv();
          break;
        case 80:
          $$.rdio_dv = 'p';
          $$.change_dv();
          break;
        case 87:
          $$.rdio_dv = 'w';
          $$.change_dv();
          break;
        case 78:
          $$.rdio_dv = 'm';
          $$.change_dv();
          break;
        case 79:
          $$.rdio_dv = 'o';
          $$.change_dv();
          break;
        case 84:
          $$.rdio_dv = 't';
          $$.change_dv();
          break;
        case 72:
          $("#modal_aide").modal(show);
      }
      return rac.reset;
    };
    raz_bd_empty = function(t_itre, b_ody) {
      if (t_itre == null) {
        t_itre = 'Filtre trop restrictif';
      }
      if (b_ody == null) {
        b_ody = ' Remise à zéro des filtres';
      }
      $$.open_modal({
        title: t_itre,
        body: b_ody,
        job: 'Raz'
      });
      $$.rdio_action = 'raz';
      $$.raz_filtre();
      $$.change_2_dates();
      return $$.board.debut = true;
    };
    $$.raz_if_bd_empty = function() {
      try {
        if ($$.gbd_filtree.length > 0) {
          $$.board.debut = false;
        }
        if ($$.gbd_filtree.length < 1 && !$$.board.debut) {
          $$.open_modal({
            title: 'Filtres trop restrictifs',
            body: ' Remise à zéro des filtres',
            job: 'Raz'
          });
          $$.rdio_action = 'raz';
          $$.raz_filtre();
          if (!$$.board.debut) {
            $$.board.debut = true;
          }
          return true;
        }
      } catch (error1) {}
      return false;
    };
  });

  window.date_to_string = function(d) {
    return new Date(new Date(d).getTime() - 1 * (new Date().getTimezoneOffset() * 60 * 1000)).toISOString().slice(0, 10);
  };

  window.sign = function(x) {
    if (x < 0) {
      return -1;
    } else {
      return 1;
    }
  };

  Raccourcis = (function() {
    function Raccourcis() {
      this.montre = bind(this.montre, this);
      this.keydown = false;
      this.code_down = 0;
      this.ts_down = this.ts_up = 0;
      this.short = true;
    }

    Raccourcis.prototype.get_event = function(e) {
      if (e.type === 'keydown' && this.keydown === false) {
        this.keydown = true;
        this.code_down = e.keyCode;
        return this.ts_down = e.timeStamp;
      } else if (e.type === 'keyup') {
        this.keydown = false;
        this.ts_up = e.timeStamp;
        return this.short = this.is_short();
      }
    };

    Raccourcis.prototype.montre = function() {
      var stg;
      return stg = ("code_down: " + this.code_down + " | ts_down : " + this.ts_down + " | ts_up : " + this.ts_up + " |  short: " + this.short + " | time:") + this.get_time();
    };

    Raccourcis.prototype.get_time = function() {
      return this.ts_up - this.ts_down;
    };

    Raccourcis.prototype.is_short = function() {
      return this.get_time() < 1000;
    };

    Raccourcis.prototype.reset = function() {
      this.code_down = this.ts_down = this.ts_up = 0;
      return this.short = false;
    };

    Raccourcis.prototype.flip = function(dom, flip_on_off) {
      switch (flip_on_off) {
        case 'flip':
          return !dom;
        case 'on':
          return true;
        case 'off':
          return false;
      }
    };

    return Raccourcis;

  })();

  window.pourcentage = function(a, b) {
    var c;
    a = parseFloat(a);
    b = parseFloat(b);
    if (b === 0) {
      return 0/0;
    }
    c = (a / b - 1) * 100;
    if (a >= b) {
      c = sign(c) * c;
    } else {
      if (b > a) {
        c = sign(c) * (-1) * c;
      }
    }
    return c;
  };

  window.Number.prototype.pourcentage = function(b) {
    var a, c;
    a = this.valueOf();
    b = parseFloat(b);
    if (b === 0) {
      return 0/0;
    }
    c = (a / b - 1) * 100;
    if (a >= b) {
      return sign(c) * c;
    }
    if (b > a) {
      return sign(c) * (-1) * c;
    }
  };

  if (!Array.prototype.filter) {
    Array.prototype.filter = function(callback) {
      var element, k, len, ref, results;
      ref = this;
      results = [];
      for (k = 0, len = ref.length; k < len; k++) {
        element = ref[k];
        if (callback(element)) {
          results.push(element);
        }
      }
      return results;
    };
  }

  window.Array.prototype.where = function(query) {
    var hit;
    if (typeof query !== "object") {
      return [];
    }
    hit = Object.keys(query).length;
    return this.filter(function(item) {
      var key, match, val;
      match = 0;
      for (key in query) {
        val = query[key];
        if (item[key] === val) {
          match += 1;
        }
      }
      if (match === hit) {
        return true;
      } else {
        return false;
      }
    });
  };

  window.marge_var_abs = function(a, b) {
    var c, d;
    c = a.Var_marge * sign(a.Var_marge);
    d = b.Var_marge * sign(b.Var_marge);
    if (c > d) {
      return -1;
    } else if (c < d) {
      return 1;
    }
    return 0;
  };

  window.clic_var_abs = function(a, b) {
    var c, d;
    c = a.Var_clic * sign(a.Var_clic);
    d = b.Var_clic * sign(b.Var_clic);
    if (c > d) {
      return -1;
    } else if (c < d) {
      return 1;
    }
    return 0;
  };

  window.marge_var_rel = function(a, b) {
    var c, d;
    c = a.Var_marge_relative * sign(a.Var_marge_relative);
    d = b.Var_marge_relative * sign(b.Var_marge_relative);
    if (c > d) {
      return -1;
    } else if (c < d) {
      return 1;
    }
    return 0;
  };

  window.clic_var_rel = function(a, b) {
    var c, d;
    c = a.Var_clic_relative * sign(a.Var_clic_relative);
    d = b.Var_clic_relative * sign(b.Var_clic_relative);
    if (c > d) {
      return -1;
    } else if (c < d) {
      return 1;
    }
    return 0;
  };

}).call(this);

//# sourceMappingURL=01_ctl_mrc.js.map
