// Generated by CoffeeScript 1.10.0
(function() {
  window.angular.module('app_mrc').controller('ModalInstanceCtrl', function($scope, $uibModalInstance, to_modal) {
    var $$, ref;
    $$ = $scope;
    $$.modal_job = to_modal;
    if ((ref = $$.modal_job.job) === 'Raz' || ref === 'Dv') {
      $$.modal_job.button_style = 'background-color: MistyRose;  border-color: silver;';
      $$.modal_job.title_style = 'background-color: MistyRose;  border-color: red; color: #3333ff;';
    }
    return $scope.cancel = function() {
      return $uibModalInstance.close('I come from modal');
    };
  });

}).call(this);

//# sourceMappingURL=05_modal.js.map
