// Generated by CoffeeScript 1.10.0
(function() {
  var MA, temps, top_init,
    slice = [].slice;

  MA = window.angular.module('app_mrc');

  top_init = new Date();

  MA.wait_ms = function(ms) {
    var laps, results1, top;
    top = new Date();
    laps = new Date();
    results1 = [];
    while (laps - top < ms) {
      results1.push(laps = new Date());
    }
    return results1;
  };

  temps = function() {
    var elt, ms, s;
    elt = new Date() - top_init;
    s = Math.floor(elt / 1000);
    ms = elt - 1000 * s;
    if (s === 0) {
      return ms.toString() + ' ms';
    }
    return s.toString() + 's ' + ms + ' ms';
  };

  MA.shw = function(x, in_fle) {
    var bgg, black, blue, t, top;
    if (typeof present_file !== "undefined" && present_file !== null) {
      in_fle = present_file;
    }
    blue = "color : #0333ff;";
    black = "color : #000000;";
    bgg = "background-color: #e6ffe6;";
    t = temps();
    top = typeof x;
    if (top === 'object') {
      if (in_fle == null) {
        console.log("%c " + t, blue);
        return console.log(x);
      } else {
        console.log("%c " + t + " - in [" + in_fle + "] -", blue);
        return console.log(x, blue);
      }
    } else {
      if (in_fle == null) {
        return console.log("%c " + t + " -[" + top + "] - %c " + x, blue, bgg);
      } else {
        return console.log("%c " + t + " - in [" + in_fle + "] -[" + top + "]-  %c " + x + " ", blue, bgg);
      }
    }
  };

  MA.shws = function() {
    var f, first, i, in_file, j, len, results1;
    first = 2 <= arguments.length ? slice.call(arguments, 0, i = arguments.length - 1) : (i = 0, []), in_file = arguments[i++];
    results1 = [];
    for (j = 0, len = first.length; j < len; j++) {
      f = first[j];
      results1.push(MA.shw(f, in_file));
    }
    return results1;
  };

  MA.show_err = function(mess, e) {
    return console.warn(mess, present_file + 'erreur : ' + e + ': traitée');
  };

  MA.wait_ms = function(ms) {
    var laps, results1, top;
    top = new Date();
    laps = new Date();
    results1 = [];
    while (laps - top < ms) {
      results1.push(laps = new Date());
    }
    return results1;
  };

  window.is_infinite = function(n) {
    return n === Number.NEGATIVE_INFINITY || n === Number.POSITIVE_INFINITY;
  };

  window.Number.prototype.format = function(t, plus_on_off) {
    var rtn, val;
    if (t == null) {
      t = 0;
    }
    if (plus_on_off == null) {
      plus_on_off = true;
    }
    val = this.valueOf();
    rtn = val.toFixed(t);
    if ((val > 1e300) || (val < -1e300) || isNaN(val)) {
      return '';
    }
    rtn.toLocaleString();
    if (val > 0 && plus_on_off) {
      rtn = '+' + rtn;
    }
    return rtn;
  };

  window.Number.prototype.hide_infinity = function() {
    if (is_infinite(this.valueof())) {
      return '';
    } else {
      return this.valueof();
    }
  };

  window.date_to_string = function(d) {
    return new Date(new Date(d).getTime() - (new Date().getTimezoneOffset() * 60 * 1000)).toISOString().slice(0, 10);
  };

  window.get_url_param = function(param) {
    var c, i, len, ref, regex, regexS, results, url;
    if (param == null) {
      param = 'parametre';
    }
    url = window.location.href;
    param = param.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
    regexS = "[\\?&]" + param + "=([^&#]*)";
    regex = new RegExp(regexS);
    results = regex.exec(url);
    if (results != null) {
      ref = ["\\", "/"];
      for (i = 0, len = ref.length; i < len; i++) {
        c = ref[i];
        results[1] = results[1].replace(c, "");
      }
      return results[1];
    } else {
      return null;
    }
  };

  window.wait_ms = function(ms) {
    var laps, results1, top;
    top = new Date();
    laps = new Date();
    results1 = [];
    while (laps - top < ms) {
      results1.push(laps = new Date());
    }
    return results1;
  };

}).call(this);

//# sourceMappingURL=06_tools.js.map
