// Generated by CoffeeScript 1.10.0

/*
---------------------------
 Created by apch on 11/03/2016.
---------------------------
 */

(function() {
  angular.module('ngClipboard', []).factory('ngClipboard', function($compile, $rootScope, $document) {
    return {
      toClipboard: function(element) {
        var body, copyElement, msg, ngClipboardElement, range, successful;
        copyElement = angular.element('<span id="ngClipboardCopyId">' + element + '</span>');
        body = $document.find('body').eq(0);
        body.append($compile(copyElement)($rootScope));
        ngClipboardElement = angular.element(document.getElementById('ngClipboardCopyId'));
        console.log(ngClipboardElement);
        range = document.createRange();
        range.selectNode(ngClipboardElement[0]);
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
        successful = document.execCommand('copy');
        msg = successful ? 'successful' : 'unsuccessful';
        console.log('Copying text command was ' + msg);
        window.getSelection().removeAllRanges();
        copyElement.remove();
      }
    };
  }).directive('ngCopyable', function() {
    var link;
    link = function(scope, element, attrs) {
      element.bind('click', function() {
        var range, successful;
        range = document.createRange();
        range.selectNode(document.getElementById("hidden_table"));
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(range);
        successful = document.execCommand('copy');
        window.getSelection().removeAllRanges();
      });
    };
    return {
      restrict: 'A',
      link: link
    };
  });

}).call(this);

//# sourceMappingURL=07_ngclipboard.js.map
