// Generated by CoffeeScript 1.10.0

/*
  ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ *
  couleurs des courbes
  le 02-04-2016
  ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ ~ ¨¨¨¨¨¨¨¨¨¨¨¨ *
 */

(function() {
  var MA;

  MA = window.angular.module('app_mrc');

  MA.pie_colors = ['#ff0333', '#03ff33', '#0333ff', '#fffc03', '#ff0033', '#888888', '#bf0000', '#00bf00', '#0000bf', '#fffc03', '#9900bf', '#ff6600', '#333333', '#ff9999', '#99ff99', '#99ccff', '#ffff99', '#cc66ff', '#cccccc', '#ffcc99', '#ffbfbf', '#ccffff', '#ffff99', '#bfbfff', '#bfff99', '#e6ccff'];

  MA.coul = function(min, max, val, rouge, orange, vert) {
    var rslt;
    if (rouge == null) {
      rouge = 'red';
    }
    if (orange == null) {
      orange = 'darkorchid';
    }
    if (vert == null) {
      vert = 'seagreen';
    }
    if (val <= min) {
      rslt = "color : " + rouge + "; font-weight: bold;";
    } else if (val >= max) {
      rslt = "color : " + vert + ";font-weight: bold;";
    } else {
      rslt = "color : " + orange + ";font-weight: bold;";
    }
    return rslt;
  };

  MA.coul_2 = function(min, max, val, rouge, orange, vert) {
    var rslt;
    if (rouge == null) {
      rouge = 'red';
    }
    if (orange == null) {
      orange = 'darkorchid';
    }
    if (vert == null) {
      vert = 'seagreen';
    }
    if (val <= min) {
      rslt = "nb_rouge";
    } else if (val >= max) {
      rslt = "nb_vert";
    } else {
      rslt = "nb_orange";
    }
    return rslt;
  };

}).call(this);

//# sourceMappingURL=09_couleurs_courbes.js.map
